spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: chat-app
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  public-endpoint: ${S3_PUBLIC_ENDPOINT:http://localhost:9000}
  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}
  bucket: ${S3_BUCKET:media}
  region: ${S3_REGION:us-east-1}
